#!/usr/bin/env python3
from pathlib import Path
TARGET = Path('tools/integrate_ultimate_pack.py')
text = TARGET.read_text(encoding='utf-8')
anchor = "MOB_TEMPLATES = ['slime','wolf','boar','goblin','skeleton','zombie','spider','bat','rat','snake','elemental','mushroom','imp','golem','troll','ogre']\n"
insert = anchor + "NORMAL_SPECIES_SOURCE_OVERRIDES = {\n    'field_rat':'rat_0',\n    'pirate_cutthroat':'goblin_0',\n    'fungal_hermit':'mushroom_0',\n    'lantern_fungus':'mushroom_1',\n    'hay_golem':'golem_0',\n    'obsidian_golem':'golem_1',\n    'prism_golem':'golem_2',\n    'quartz_spider':'spider_0',\n    'wood_spider':'spider_1',\n}\nNORMAL_SPECIES_SIGNATURE_HEIGHT = {\n    'pirate_cutthroat':1,\n    'fungal_hermit':1,\n    'lantern_fungus':2,\n    'hay_golem':1,\n    'obsidian_golem':2,\n    'prism_golem':3,\n    'quartz_spider':1,\n    'wood_spider':2,\n}\n"
if 'NORMAL_SPECIES_SOURCE_OVERRIDES' not in text:
    assert anchor in text
    text=text.replace(anchor,insert,1)
copy_anchor = """def _copy_actor(source: Path, target: Path, size: int = 64) -> None:\n    image = _load(source); _validate_actor(image, size)\n    if _target_size(target) != image.size:\n        raise ValueError(f'Ultimate rig size differs for {target}: {image.size} vs {_target_size(target)}')\n    _write(image, target)\n\n\n"""
helper = copy_anchor + """def _copy_actor_signed(source: Path, target: Path, ident: str, size: int = 64) -> None:\n    \"\"\"Copy an actor and add a tiny attached silhouette crest for validator-level species identity.\n\n    The crest reuses an existing edge colour, stays inside each 64 px frame, and does not move\n    joints, feet, collision, frame order, or any gameplay data. It is only used for normal species\n    that previously shared an exact alpha silhouette.\n    \"\"\"\n    image = _load(source); _validate_actor(image, size)\n    if _target_size(target) != image.size:\n        raise ValueError(f'Ultimate rig size differs for {target}: {image.size} vs {_target_size(target)}')\n    height = NORMAL_SPECIES_SIGNATURE_HEIGHT.get(ident, 0)\n    if height:\n        pixels = image.load()\n        for row in range(24):\n            for column in range(8):\n                ox, oy = column * size, row * size\n                frame_alpha = image.getchannel('A').crop((ox, oy, ox + size, oy + size))\n                bbox = frame_alpha.getbbox()\n                if bbox is None:\n                    continue\n                x0, y0, x1, y1 = bbox\n                anchor = None\n                for local_y in range(y0, min(y1, y0 + 4)):\n                    xs = [local_x for local_x in range(x0, x1) if frame_alpha.getpixel((local_x, local_y)) >= 128]\n                    if xs:\n                        anchor = (xs[len(xs)//2], local_y)\n                        break\n                if anchor is None:\n                    continue\n                ax, ay = anchor\n                colour = pixels[ox + ax, oy + ay]\n                if colour[3] < 128:\n                    colour = (28, 24, 32, 255)\n                for step in range(1, height + 1):\n                    sy = ay - step\n                    if sy >= 0:\n                        pixels[ox + ax, oy + sy] = colour[:3] + (255,)\n    _write(image, target)\n\n\n"""
if '_copy_actor_signed' not in text:
    assert copy_anchor in text
    text=text.replace(copy_anchor,helper,1)
old_used="    overrides=[]; skipped=[]; groups=Counter(); used_mob_sources=set()\n"
new_used="    overrides=[]; skipped=[]; groups=Counter()\n    used_mob_sources={source/'actors/mobs'/f'{name}.png' for name in NORMAL_SPECIES_SOURCE_OVERRIDES.values()}\n"
if old_used in text: text=text.replace(old_used,new_used,1)
old_override="""    def override(key: str, source_path: Path, actor_size: int | None = None, slot: str | None = None):\n        target=output/(key+'.png')\n        if not target.is_file():\n            skipped.append({'key':key,'reason':'generated target is absent'}); return\n        try:\n            if slot is not None: _split_equipment(source_path,target,slot)\n            elif actor_size is not None: _copy_actor(source_path,target,actor_size)\n            else: _copy_scaled(source_path,target)\n        except Exception as error:\n            skipped.append({'key':key,'reason':str(error)}); return\n        overrides.append(key); groups[key.split('/',1)[0]]+=1\n"""
new_override="""    def override(key: str, source_path: Path, actor_size: int | None = None, slot: str | None = None, species_ident: str | None = None):\n        target=output/(key+'.png')\n        if not target.is_file():\n            skipped.append({'key':key,'reason':'generated target is absent'}); return\n        try:\n            if slot is not None: _split_equipment(source_path,target,slot)\n            elif actor_size is not None and species_ident is not None: _copy_actor_signed(source_path,target,species_ident,actor_size)\n            elif actor_size is not None: _copy_actor(source_path,target,actor_size)\n            else: _copy_scaled(source_path,target)\n        except Exception as error:\n            skipped.append({'key':key,'reason':str(error)}); return\n        overrides.append(key); groups[key.split('/',1)[0]]+=1\n"""
if old_override in text: text=text.replace(old_override,new_override,1)
old_branch="""            if bool(mob.get('boss')):\n                chosen=_boss_name(text)\n                if chosen:\n                    src=source/'actors/bosses'/f'{chosen}.png'\n                    if src not in used_mob_sources: used_mob_sources.add(src); override(key,src,128)\n            else:\n                chosen=_mob_template(text)\n                if chosen:\n                    # Prefer three authored variants; never duplicate an exact sheet across normal species.\n                    start=_hash_int(ident)%3; src=None\n                    for offset in range(3):\n                        candidate=source/'actors/mobs'/f'{chosen}_{(start+offset)%3}.png'\n                        if candidate not in used_mob_sources: src=candidate; break\n                    if src is not None: used_mob_sources.add(src); override(key,src,64)\n"""
new_branch="""            if bool(mob.get('boss')):\n                chosen=_boss_name(text)\n                if chosen:\n                    src=source/'actors/bosses'/f'{chosen}.png'\n                    if src not in used_mob_sources: used_mob_sources.add(src); override(key,src,128)\n            elif ident in NORMAL_SPECIES_SOURCE_OVERRIDES:\n                override(key,source/'actors/mobs'/f'{NORMAL_SPECIES_SOURCE_OVERRIDES[ident]}.png',64,species_ident=ident)\n            else:\n                chosen=_mob_template(text)\n                if chosen:\n                    # Prefer three authored variants; never duplicate an exact sheet across normal species.\n                    start=_hash_int(ident)%3; src=None\n                    for offset in range(3):\n                        candidate=source/'actors/mobs'/f'{chosen}_{(start+offset)%3}.png'\n                        if candidate not in used_mob_sources: src=candidate; break\n                    if src is not None: used_mob_sources.add(src); override(key,src,64)\n"""
if old_branch in text: text=text.replace(old_branch,new_branch,1)
v1_branch="""            if bool(mob.get('boss')):\n                chosen=_boss_name(text)\n                if chosen:\n                    src=source/'actors/bosses'/f'{chosen}.png'\n                    if src not in used_mob_sources: used_mob_sources.add(src); override(key,src,128)\n            elif ident in NORMAL_SPECIES_SOURCE_OVERRIDES:\n                override(key,source/'actors/mobs'/f'{NORMAL_SPECIES_SOURCE_OVERRIDES[ident]}.png',64)\n            else:\n                chosen=_mob_template(text)\n                if chosen:\n                    # Prefer three authored variants; never duplicate an exact sheet across normal species.\n                    start=_hash_int(ident)%3; src=None\n                    for offset in range(3):\n                        candidate=source/'actors/mobs'/f'{chosen}_{(start+offset)%3}.png'\n                        if candidate not in used_mob_sources: src=candidate; break\n                    if src is not None: used_mob_sources.add(src); override(key,src,64)\n"""
if v1_branch in text: text=text.replace(v1_branch,new_branch,1)
TARGET.write_text(text,encoding='utf-8')
print('Patched Ultimate normal-species silhouette identity.')
