#!/usr/bin/env python3
"""Build the Foundry pack: effects, terrain transitions, interface, portraits.

Foundry is supplementary to the Atelier sprite library — it draws with Atelier's
engine but writes only inside foundry/. It touches nothing under atelier/,
client/ or content/.

    python foundry/build.py                  # everything, then pack atlases
    python foundry/build.py --only ui vfx
    python foundry/build.py --list
    python foundry/build.py --atlas          # repack what is already on disk
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(ROOT / 'atelier'))

from PIL import Image  # noqa: E402

from kit import atlas, face, ground, portraits, vfx  # noqa: E402

OUT = HERE / 'Assets'
CATALOG = ROOT / 'content' / 'catalog.json'
GROUPS = ('vfx', 'ground', 'ui', 'portraits')
ANIMATED = {'vfx'}


def catalogue():
    if not CATALOG.is_file():
        return None
    return json.loads(CATALOG.read_text(encoding='utf-8'))


def plan(groups):
    """(group, key, frames) tuples. frames > 1 means a horizontal strip."""
    tasks = []
    if 'vfx' in groups:
        for key, size, _ in vfx.plan():
            tasks.append(('vfx', key, size))
    if 'ground' in groups:
        for key, _ in ground.plan():
            tasks.append(('ground', key, 0))
    if 'ui' in groups:
        for key, _ in face.plan():
            tasks.append(('ui', key, 0))
    if 'portraits' in groups:
        for key, _ in portraits.plan(catalogue()):
            tasks.append(('portraits', key, 0))
    return tasks


_MAKERS = None


def makers():
    """Rebuilt per worker process; lambdas cannot cross a process boundary."""
    global _MAKERS
    if _MAKERS is None:
        _MAKERS = {}
        for key, size, maker in vfx.plan():
            _MAKERS[key] = ('vfx', size, maker)
        for key, maker in ground.plan():
            _MAKERS[key] = ('ground', 0, maker)
        for key, maker in face.plan():
            _MAKERS[key] = ('ui', 0, maker)
        for key, maker in portraits.plan(catalogue()):
            _MAKERS[key] = ('portraits', 0, maker)
    return _MAKERS


def render(task):
    group, key, size = task
    entry = makers().get(key)
    if entry is None:
        raise KeyError('no maker for ' + key)
    _, frame_size, maker = entry
    if group == 'vfx':
        image = vfx.strip(maker, frame_size)
    else:
        image = maker()
    if image.mode != 'RGBA':
        image = image.convert('RGBA')
    path = OUT / (key + '.png')
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path, optimize=True, compress_level=9)
    return key, group


def manifest():
    entries = []
    for path in sorted(OUT.rglob('*.png')):
        key = path.relative_to(OUT).with_suffix('').as_posix()
        if key.startswith('atlas'):        # generated pages are not source assets
            continue
        group = key.split('/', 1)[0]
        with Image.open(path) as image:
            if image.mode != 'RGBA':
                raise ValueError('Not RGBA: ' + key)
            if image.getchannel('A').getbbox() is None:
                raise ValueError('Blank asset: ' + key)
            frames = 1
            if group in ANIMATED:
                frames = vfx.FRAMES
                if image.width % frames:
                    raise ValueError('Bad strip width: ' + key)
            entries.append({
                'key': key, 'group': group, 'width': image.width, 'height': image.height,
                'frames': frames,
                'sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
            })
    return entries


CREDITS = """Kairnfall Foundry pack.

Everything here is generated by the source in foundry/kit, drawing with the
Atelier engine in atelier/forge. No third party art is included and nothing is
copied from any other pack in this repository.

Effect strips run left to right, eight frames, one row. One-shots end on an
empty frame; auras and projectiles loop. Terrain overlays are drawn on top of a
base tile and are keyed by a four bit neighbour mask (1 north, 2 east, 4 south,
8 west). Interface panels are nine-slice sources, 48x48 with 16px corners.
Portraits are 64x64; player portraits layer a base and a hair overlay the same
way the world sprites do.

Structural checks confirm files exist, are RGBA, are not blank and have sane
strip widths. That is not artistic approval.
"""


# Animation sheets are already atlases; packing them again just makes pages
# too big to be useful. The win is in the thousands of small icons and tiles.
LOOSE_GROUPS = ('items', 'gear', 'abilities', 'skills', 'terrain', 'props', 'chests',
                'resources', 'structures')


def pack_atelier():
    """Pack the sibling Atelier pack's small art into atlases, without touching it."""
    source = ROOT / 'atelier' / 'Assets'
    if not source.is_dir():
        print('FOUNDRY: no atelier/Assets to pack', flush=True)
        return None
    entries = []
    skipped = 0
    for group in LOOSE_GROUPS:
        folder = source / group
        if not folder.is_dir():
            continue
        for key, path in atlas.collect(folder):
            with Image.open(path) as image:
                entries.append(('%s/%s' % (group, key), image.convert('RGBA').copy()))
    if not entries:
        print('FOUNDRY: nothing to pack from atelier', flush=True)
        return None
    out = OUT / 'atlas_atelier'
    out.mkdir(parents=True, exist_ok=True)
    pages, placements, oversized = atlas.pack(entries, atlas.PAGE)
    for index, image in enumerate(pages):
        image.save(out / ('atelier_%d.png' % index), optimize=True, compress_level=9)
    report = {
        'schema': 1,
        'source': 'atelier/Assets (read only)',
        'page_size': atlas.PAGE,
        'padding': atlas.PADDING,
        'pages': ['atelier_%d.png' % index for index in range(len(pages))],
        'occupancy': atlas.occupancy(pages, placements),
        'packed': len(placements),
        'too_large_for_a_page': oversized,
        'frames': placements,
    }
    (out / 'atelier.json').write_text(json.dumps(report, indent=1) + '\n', encoding='utf-8')
    print('FOUNDRY: packed %d atelier images onto %d pages (%s)'
          % (len(placements), len(pages),
             ', '.join('%.0f%%' % (value * 100) for value in report['occupancy'])), flush=True)
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--only', nargs='+', choices=GROUPS, default=list(GROUPS))
    parser.add_argument('--jobs', type=int, default=max(1, (os.cpu_count() or 2) - 1))
    parser.add_argument('--list', action='store_true')
    parser.add_argument('--atlas', action='store_true', help='repack atlases only')
    parser.add_argument('--no-atlas', action='store_true', help='skip atlas packing')
    parser.add_argument('--pack-atelier', action='store_true',
                        help='also pack the Atelier icon and tile set into atlases')
    args = parser.parse_args()

    if args.pack_atelier:
        pack_atelier()
        if args.atlas:
            return

    groups = set(args.only)
    tasks = [] if args.atlas else plan(groups)
    if args.list:
        counts = {}
        for group, _, _ in plan(set(GROUPS)):
            counts[group] = counts.get(group, 0) + 1
        for group in GROUPS:
            print('%-11s %5d' % (group, counts.get(group, 0)))
        print('%-11s %5d' % ('total', sum(counts.values())))
        return

    OUT.mkdir(parents=True, exist_ok=True)
    start = time.time()
    if tasks:
        print('FOUNDRY: %d assets -> %s' % (len(tasks), OUT), flush=True)
        if args.jobs > 1:
            with ProcessPoolExecutor(max_workers=args.jobs) as pool:
                for index, _ in enumerate(pool.map(render, tasks, chunksize=4), 1):
                    if index % 100 == 0 or index == len(tasks):
                        print('  %5d / %d  (%.0fs)' % (index, len(tasks), time.time() - start),
                              flush=True)
        else:
            for index, task in enumerate(tasks, 1):
                render(task)
                if index % 100 == 0 or index == len(tasks):
                    print('  %5d / %d  (%.0fs)' % (index, len(tasks), time.time() - start),
                          flush=True)

    entries = manifest()
    report = None
    if not args.no_atlas:
        print('FOUNDRY: packing atlases', flush=True)
        report = atlas.build(OUT, OUT / 'atlas', 'foundry',
                             exclude=('atlas', 'atlas_atelier'))
    (OUT / 'manifest.json').write_text(json.dumps({
        'schema': 1,
        'pack': 'foundry',
        'source': 'Generated by foundry/kit using the atelier/forge engine.',
        'artistic_review': 'pending',
        'effect_frames': vfx.FRAMES,
        'nine_slice': {'size': face.SLICE, 'corner': face.CORNER},
        'terrain_mask': {'north': 1, 'east': 2, 'south': 4, 'west': 8},
        'assets': entries,
    }, indent=2) + '\n', encoding='utf-8')
    (OUT / 'CREDITS.txt').write_text(CREDITS, encoding='utf-8')
    tally = {}
    for entry in entries:
        tally[entry['group']] = tally.get(entry['group'], 0) + 1
    coverage = {
        'groups': tally,
        'png_files': len(entries),
        'effect_strips': sum(1 for entry in entries if entry['frames'] > 1),
        'built_seconds': round(time.time() - start, 1),
        'artistic_review': 'pending',
    }
    if report:
        coverage['atlas'] = {'pages': len(report['pages']), 'packed': report['packed'],
                             'occupancy': report['occupancy'],
                             'too_large': report['too_large_for_a_page']}
    (HERE / 'coverage.json').write_text(json.dumps(coverage, indent=2) + '\n', encoding='utf-8')
    print('FOUNDRY RESULT: %d images (%d effect strips)%s in %.0fs. '
          'Structural checks passed; visual review is still required.'
          % (len(entries), coverage['effect_strips'],
             '' if not report else ', %d atlas pages' % len(report['pages']),
             coverage['built_seconds']), flush=True)


if __name__ == '__main__':
    main()
